# Generated by Django 2.2.1 on 2019-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
